release: python manage.py migrate
{%- if cookiecutter.use_async == "y" -%}
web: gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker
{%- else  %}
web: gunicorn config.wsgi:application
{%- endif %}
